# Build and release binaries for all major os/archs

name: Release to Github
on:
  push:
    tags:
      - 'mmdbctl-*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release to Github
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup GO
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Extract version from tag
      run: echo "CLI_VERSION=${GITHUB_REF_NAME#mmdbctl-}" >> "$GITHUB_ENV"

    - name: Build
      run: ./scripts/build-archive-all.sh ${{ env.CLI_VERSION }}

    - name: Generate changelog
      run: ./scripts/changelog.sh ${{ env.CLI_VERSION }} > changes.md

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: changes.md
        files: |
          ./build/mmdbctl_${{ env.CLI_VERSION }}*.tar.gz
          ./build/mmdbctl_${{ env.CLI_VERSION }}*.zip
          ./build/mmdbctl_${{ env.CLI_VERSION }}*.deb
          ./build/mmdbshrink_${{ env.CLI_VERSION }}*.tar.gz
          ./build/mmdbshrink_${{ env.CLI_VERSION }}*.zip
          ./macos.sh
          ./windows.ps1
          ./deb.sh
